trigger:
  batch: true
  branches:
    include:
    - main
    - 'v17.*'
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - azure-pipelines/release.yml
    - azure-pipelines/vs-insertion.yml
schedules:
- cron: "0 3 * * *" # Daily @ 8 PM PST
  displayName: Daily vs-insertion
  branches:
    include:
    - main

parameters:
- name: SignTypeSelection
  displayName: Sign type
  type: string
  default: Test
  values: [ 'Test', 'Real' ]
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true
- name: EnableCompliance
  displayName: Run Compliance Tools
  type: boolean
  default: true
- name: EnableAPIScan
  displayName: Include APIScan with Compliance tools
  type: boolean
  default: true

stages:

- stage: Build
  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
    SignTypeSelection: ${{ parameters.SignTypeSelection }}
    Packaging.EnableSBOMSigning: false
    Codeql.Enabled: true

  jobs:
  - template: build.yml
    parameters:
      EnableCompliance: ${{ parameters.EnableCompliance }}
      EnableAPIScan: ${{ parameters.EnableAPIScan }}
      windowsPool: VSEngSS-MicroBuild2022-1ES
      RunTests: ${{ parameters.RunTests }}

- template: prepare-insertion-stages.yml
